"""add category table and post category_id

Revision ID: 26cbbd051d59
Revises: 51d2e98ed6f8
Create Date: 2026-08-29 23:45:55.247172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '26cbbd051d59'
down_revision: Union[str, Sequence[str], None] = '51d2e98ed6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.add_column('post', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_post_category_id'), 'post', ['category_id'], unique=False)
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_category_id'), table_name='post')
    op.drop_column('post', 'category_id')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
